networks:
  my_net:
    driver: bridge
 
services:
  sequencer:
    environment:
      - MEMBERS_NUM=${MEMBERS_NUM}
      - REGISTRATION_PORT=${REGISTRATION_PORT}
      - LISTENING_PORT=${SEQUENCER_PORT}
      - PEER_PORT=${MULTICAST_PORT}
      - DELAY=${DELAY}
    build:
      context: ..
      dockerfile: deployments/sequencer/Dockerfile
    image: sequencer_service
    container_name: sequencer
    profiles:
      - sequencer
    depends_on:
      - "registration"
    networks:
      - my_net
    ports:
      - ${SEQUENCER_PORT}
  peer:
    environment:
      - MEMBERS_NUM=${MEMBERS_NUM}
      - REGISTRATION_PORT=${REGISTRATION_PORT}
      - MULTICAST_PORT=${MULTICAST_PORT}
      - SEQUENCER_PORT=${SEQUENCER_PORT}
      - CONTROL_PORT=${CONTROL_PORT}
      - MULTICAST_ALGORITHM=${MULTI_ALGO}
      - DELAY=${DELAY}
    build:
      context: ..
      dockerfile: deployments/peer/Dockerfile
    image: peer_service
    scale: ${MEMBERS_NUM}
    depends_on:
      - "registration"
    networks:
      - my_net
    ports:
      - ${MULTICAST_PORT}
      - ${CONTROL_PORT}
  registration:
    environment:
      - LISTENING_PORT=${REGISTRATION_PORT}
      - MEMBERS_NUM=${MEMBERS_NUM}
      - MULTICAST_ALGORITHM=${MULTI_ALGO}
    build:
      context: ..
      dockerfile: deployments/registration/Dockerfile
    image: registration_service
    container_name: registry
    networks:
      - my_net
    ports:
      - ${REGISTRATION_PORT}
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    logging:
      driver: "none"
    networks:
      - my_net
    ports:
      - 27017