networks:
  my_net:
    driver: bridge
 
services:
  peer:
    environment:
      - MEMBERS_NUM=${MEMBERS_NUM}
      - REGISTRATION_PORT=${REGISTRATION_PORT}
      - MULTICAST_PORT=${MULTICAST_PORT}
      - CONTROL_PORT=${CONTROL_PORT}
    build:
      context: ..
      dockerfile: deployments/peer/Dockerfile
    image: service_client
    scale: ${MEMBERS_NUM}
    depends_on:
      - "registration"
    networks:
      - my_net
    ports:
      - ${MULTICAST_PORT}
      - ${CONTROL_PORT}
  registration:
    environment:
      - LISTENING_PORT=${REGISTRATION_PORT}
      - MEMBERS_NUM=${MEMBERS_NUM}
    build:
      context: ..
      dockerfile: deployments/registration/Dockerfile
    image: registration_service
    networks:
      - my_net
    ports:
      - ${REGISTRATION_PORT}