networks:
  my_net:
    driver: bridge
 
services:
  peer:
    environment:
      - MEMBERS_NUM=${MEMBERS_NUM}
      - REGISTRY_PORT=${REGISTRY_PORT}
    build:
      context: ../internal
      dockerfile: ../deployments/peer/Dockerfile
    scale: ${MEMBERS_NUM}
    depends_on:
      - "registry"
    networks:
      - my_net
  registry:
    environment:
      - LISTENING_PORT=${REGISTRY_PORT}
      - MEMBERS_NUM=${MEMBERS_NUM}
    build:
      context: ../internal
      dockerfile: ../deployments/registry/Dockerfile
    volumes:
      - ../internal/registry/volume:/go/src/app/registry
    networks:
      - my_net
    ports:
      - ${REGISTRY_PORT}