networks:
  my_net:
    driver: bridge
 
services:
  peer:
    build: peer_service
    depends_on:
      - "registry"
    networks:
      - my_net
  registry:
    environment:
      - LISTENING_PORT=${REGISTRY_PORT}
    build: registry_service
    networks:
      - my_net
    ports:
      - ${REGISTRY_PORT}